name: Deploy após Merge
run-name: ${{ github.actor }} is running the CD ⚙️

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Set environment variables from secrets
        run: |
          echo "VITE_FIREBASEapiKey=${{ secrets.KEY }}" >> $GITHUB_ENV
          echo "VITE_FIREBASEauthDomain=${{ secrets.DOM }}" >> $GITHUB_ENV
          echo "VITE_FIREBASEprojectId=${{ secrets.PID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASEstorageBucket=${{ secrets.BUC }}" >> $GITHUB_ENV
          echo "VITE_FIREBASEmessagingSenderId=${{ secrets.SID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASEappId=${{ secrets.APPID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASEmeasurementId=${{ secrets.EID }}" >> $GITHUB_ENV
      
      
      - name: Construir o projeto
        run: npm run build

      - name: Instalar sshpass
        run: sudo apt-get install -y sshpass

      - name: Enviar arquivos para o servidor via SCP
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:web/NAVGUIDE
